import type { BankQuestion } from "./seedData";

// More bank questions, appended after each lesson's original questions (so
// existing question ids never shift). Keyed by "<subject>/<lesson>".
export const EXTRA_QUESTIONS: Record<string, BankQuestion[]> = {
  "math/numbers": [
    {
      q: "5⁰ = ?",
      choices: ["0", "1", "5", "Тодорхойгүй"],
      answer: 1,
      explanation: "Тэгээс ялгаатай дурын тооны 0 зэрэг 1-тэй тэнцүү.",
    },
    {
      q: "2⁻³ = ?",
      choices: ["-8", "-6", "1/8", "1/6"],
      answer: 2,
      explanation: "a⁻ⁿ = 1/aⁿ тул 2⁻³ = 1/2³ = 1/8.",
    },
    {
      q: "1/2 : 1/4 = ?",
      choices: ["1/8", "1/2", "2", "4"],
      answer: 2,
      explanation: "Бутархайд хуваахдаа урвуугаар нь үржүүлнэ: 1/2 · 4/1 = 2.",
    },
    {
      q: "4 ба 6-ын хамгийн бага ерөнхий хуваагдагч хэд вэ?",
      choices: ["10", "12", "24", "2"],
      answer: 1,
      explanation: "4-ийн үржвэрүүд: 4, 8, 12…; 6-ийн үржвэрүүд: 6, 12… Хамгийн бага нь 12.",
    },
    {
      q: "Барааны үнэ 20%-иар буурч 8000₮ болжээ. Анхны үнэ хэд байсан бэ?",
      choices: ["9600₮", "10000₮", "9000₮", "10400₮"],
      answer: 1,
      explanation: "Шинэ үнэ анхны үнийн 80% тул анхны үнэ = 8000 / 0.8 = 10000₮.",
    },
    {
      q: "√50-ийг хялбарчилна уу.",
      choices: ["5√2", "2√5", "25√2", "10√5"],
      answer: 0,
      explanation: "√50 = √(25·2) = 5√2.",
    },
    {
      q: "a² − b² = ?",
      choices: ["(a − b)²", "(a − b)(a + b)", "(a + b)²", "a² − 2ab + b²"],
      answer: 1,
      explanation: "Квадратуудын ялгаврын томьёо: a² − b² = (a − b)(a + b).",
    },
  ],
  "math/equations": [
    {
      q: "5x − 3 = 2x + 9 бол x = ?",
      choices: ["2", "3", "4", "6"],
      answer: 2,
      explanation: "5x − 2x = 9 + 3 → 3x = 12 → x = 4.",
    },
    {
      q: "x² = 49 тэгшитгэлийн шийдүүд аль нь вэ?",
      choices: ["7", "−7", "±7", "49"],
      answer: 2,
      explanation: "7² = 49 ба (−7)² = 49 тул x = ±7.",
    },
    {
      q: "−2x > 6 тэнцэтгэл бишийн шийд аль нь вэ?",
      choices: ["x > −3", "x < −3", "x > 3", "x < 3"],
      answer: 1,
      explanation: "Хоёр талыг сөрөг тоо −2-т хуваахад тэмдэг эргэнэ: x < −3.",
    },
    {
      q: "2(x + 3) = 14 бол x = ?",
      choices: ["3", "4", "5", "7"],
      answer: 1,
      explanation: "Хоёр талыг 2-т хуваавал x + 3 = 7, эндээс x = 4.",
    },
    {
      q: "|x − 2| = 5 тэгшитгэлийн шийдүүд аль нь вэ?",
      choices: ["7", "−3 ба 7", "3 ба 7", "−7 ба 3"],
      answer: 1,
      explanation: "x − 2 = 5 эсвэл x − 2 = −5 тул x = 7 эсвэл x = −3.",
    },
    {
      q: "x² + 4x + 5 = 0 тэгшитгэл хэдэн бодит шийдтэй вэ?",
      choices: ["0", "1", "2", "Хязгааргүй олон"],
      answer: 0,
      explanation: "D = 4² − 4·1·5 = −4 < 0 тул бодит шийдгүй.",
    },
    {
      q: "Хоёр тооны нийлбэр 20, ялгавар 4. Их тоо нь хэд вэ?",
      choices: ["10", "12", "14", "16"],
      answer: 1,
      explanation: "x + y = 20, x − y = 4 → 2x = 24 → x = 12.",
    },
  ],
  "math/functions": [
    {
      q: "g(x) = 2x, h(x) = x + 1 бол g(h(2)) = ?",
      choices: ["5", "6", "7", "8"],
      answer: 1,
      explanation: "Эхлээд h(2) = 3, дараа нь g(3) = 2·3 = 6.",
    },
    {
      q: "y = x + 1 ба y = −x + 3 шулуунууд аль цэгт огтлолцох вэ?",
      choices: ["(1; 2)", "(2; 3)", "(0; 1)", "(−1; 0)"],
      answer: 0,
      explanation: "x + 1 = −x + 3 → 2x = 2 → x = 1, y = 2.",
    },
    {
      q: "y = x² − 4 функцийн графикийн оройн цэг аль нь вэ?",
      choices: ["(0; 4)", "(0; −4)", "(2; 0)", "(−4; 0)"],
      answer: 1,
      explanation: "y = x² графикийг 4 нэгжээр доош шилжүүлсэн тул орой нь (0; −4).",
    },
    {
      q: "f(x) = √(x − 3) функцийн тодорхойлогдох муж аль нь вэ?",
      choices: ["x > 3", "x ≥ 3", "x ≤ 3", "Бүх бодит тоо"],
      answer: 1,
      explanation: "Язгуур доорх илэрхийлэл сөрөг биш байх ёстой: x − 3 ≥ 0 → x ≥ 3.",
    },
    {
      q: "log₂ 8 = ?",
      choices: ["2", "3", "4", "16"],
      answer: 1,
      explanation: "2³ = 8 тул log₂ 8 = 3.",
    },
    {
      q: "y = 2ˣ функц x = 0 үед ямар утга авах вэ?",
      choices: ["0", "1", "2", "Тодорхойгүй"],
      answer: 1,
      explanation: "2⁰ = 1 тул график (0; 1) цэгийг дайрна.",
    },
    {
      q: "f(x) = x² бол f(−3) = ?",
      choices: ["−9", "9", "−6", "6"],
      answer: 1,
      explanation: "(−3)² = 9. Тэгш зэрэг сөрөг тоог эерэг болгоно.",
    },
  ],
  "math/geometry": [
    {
      q: "Зэргэлдээ өнцгүүдийн нийлбэр хэд вэ?",
      choices: ["90°", "180°", "270°", "360°"],
      answer: 1,
      explanation: "Зэргэлдээ өнцгүүд шулуун өнцөг үүсгэх тул нийлбэр нь 180°.",
    },
    {
      q: "Тэгш өнцөгт гурвалжны нэг хурц өнцөг 35° бол нөгөө хурц өнцөг хэд вэ?",
      choices: ["45°", "55°", "65°", "145°"],
      answer: 1,
      explanation: "Хурц өнцгүүдийн нийлбэр 90° тул 90° − 35° = 55°.",
    },
    {
      q: "Талууд нь 5 ба 7 см тэгш өнцөгтийн периметр хэд вэ?",
      choices: ["12 см", "24 см", "35 см", "70 см"],
      answer: 1,
      explanation: "P = 2(a + b) = 2(5 + 7) = 24 см.",
    },
    {
      q: "Радиус нь 2, өндөр нь 5 цилиндрийн эзлэхүүн хэд вэ?",
      choices: ["10π", "20π", "40π", "100π"],
      answer: 1,
      explanation: "V = πr²h = π·4·5 = 20π.",
    },
    {
      q: "Суурь нь 8, өндөр нь 5 параллелограммын талбай хэд вэ?",
      choices: ["13", "26", "40", "80"],
      answer: 2,
      explanation: "S = суурь · өндөр = 8·5 = 40.",
    },
    {
      q: "Суурь нь 6 ба 10, өндөр нь 4 трапецийн талбай хэд вэ?",
      choices: ["32", "40", "64", "24"],
      answer: 0,
      explanation: "S = (a + b)/2 · h = (6 + 10)/2 · 4 = 32.",
    },
    {
      q: "Радиус нь 3 бөмбөрцгийн эзлэхүүн хэд вэ?",
      choices: ["12π", "27π", "36π", "108π"],
      answer: 2,
      explanation: "V = 4/3·πr³ = 4/3·π·27 = 36π.",
    },
  ],
  "biology/cell": [
    {
      q: "Эсийг анх 1665 онд микроскопоор ажиглаж «эс» гэж нэрлэсэн эрдэмтэн хэн бэ?",
      choices: ["Роберт Гук", "Чарльз Дарвин", "Грегор Мендель", "Луи Пастер"],
      answer: 0,
      explanation: "Роберт Гук үйсний зүсмэлийг ажиглаж, жижиг өрөөнүүдийг «cell» гэж нэрлэсэн.",
    },
    {
      q: "Уураг, липидийг ангилж, савлан тээвэрлэдэг органоид аль нь вэ?",
      choices: ["Гольджийн цогцолбор", "Рибосом", "Лизосом", "Бөөм"],
      answer: 0,
      explanation: "Гольджийн цогцолбор бодисуудыг боловсруулж, бөмбөлөгт савлан зөөдөг.",
    },
    {
      q: "Эсийн мембран ба бөөмийн хоорондох шингэн орчныг юу гэдэг вэ?",
      choices: ["Цитоплазм", "Плазм", "Лимф", "Вакуоль"],
      answer: 0,
      explanation: "Цитоплазмд органоидууд байрлаж, олон биохимийн урвал явагдана.",
    },
    {
      q: "Эсийн доторх хоол боловсруулах, хог задлах үүрэгтэй эрхтэнцэр аль нь вэ?",
      choices: ["Лизосом", "Хлоропласт", "Рибосом", "Центриоль"],
      answer: 0,
      explanation: "Лизосом дотроо хоол боловсруулах ферментүүдтэй.",
    },
    {
      q: "Митозын үр дүнд хэдэн охин эс үүсэх вэ?",
      choices: ["1", "2", "4", "8"],
      answer: 1,
      explanation: "Митозоор эхийн эстэй ижил хромосомын багцтай 2 охин эс үүснэ.",
    },
    {
      q: "Мейозын үр дүнд үүсэх эсүүд ямар хромосомын багцтай вэ?",
      choices: ["Диплоид (2n)", "Гаплоид (n)", "Триплоид (3n)", "Тетраплоид (4n)"],
      answer: 1,
      explanation: "Мейоз хромосомын тоог хоёр дахин цөөрүүлж, гаплоид үр хөврөлийн эс үүсгэнэ.",
    },
    {
      q: "Эсийн мембран юунаас голлон тогтдог вэ?",
      choices: ["Целлюлоз", "Фосфолипидын давхар үе", "Хитин", "Крахмал"],
      answer: 1,
      explanation: "Мембран нь фосфолипидын давхар үе дотор уурагууд шигдсэн бүтэцтэй.",
    },
  ],
  "biology/genetics": [
    {
      q: "Хүний бэлгийн эсэд хэдэн хромосом байдаг вэ?",
      choices: ["23", "46", "22", "92"],
      answer: 0,
      explanation: "Бэлгийн эс гаплоид (n) тул 23 хромосомтой; бордоход 46 болно.",
    },
    {
      q: "РНХ-д тиминий оронд ямар азотын суурь байдаг вэ?",
      choices: ["Аденин", "Гуанин", "Урацил", "Цитозин"],
      answer: 2,
      explanation: "РНХ-д A–U, G–C хос үүснэ; тимин зөвхөн ДНХ-д байдаг.",
    },
    {
      q: "Aa × aa огтлолцлын үр удамд давамгай шинж илрэх магадлал хэд вэ?",
      choices: ["1/4", "1/2", "3/4", "1"],
      answer: 1,
      explanation: "Үр удам Aa ба aa тэнцүү магадлалтай; давамгай шинж Aa-д илэрнэ → 1/2.",
    },
    {
      q: "Генотип нь Aa бодгалийг юу гэж нэрлэх вэ?",
      choices: ["Гомозигот", "Гетерозигот", "Гаплоид", "Мутант"],
      answer: 1,
      explanation: "Ялгаатай хоёр аллельтай бодгаль гетерозигот; AA эсвэл aa бол гомозигот.",
    },
    {
      q: "Нэг амин хүчлийг хэдэн нуклеотидын дараалал (кодон) кодлодог вэ?",
      choices: ["1", "2", "3", "4"],
      answer: 2,
      explanation: "Генетик код гурвалсан: нэг кодон = 3 нуклеотид.",
    },
    {
      q: "ДНХ-ээс мРНХ нийлэгжих процессыг юу гэдэг вэ?",
      choices: ["Трансляци", "Транскрипци", "Репликаци", "Мутаци"],
      answer: 1,
      explanation: "Транскрипци — ДНХ-ээс РНХ хуулбарлах; трансляци — РНХ-ээр уураг нийлэгжүүлэх.",
    },
    {
      q: "AA × aa огтлолцлын бүх үр удам ямар генотиптэй вэ?",
      choices: ["AA", "Aa", "aa", "AA ба aa"],
      answer: 1,
      explanation: "Эцэг эх тус бүрээс нэг аллель авах тул бүгд Aa (Менделийн 1-р хууль).",
    },
  ],
  "biology/human-body": [
    {
      q: "Хүний биеийн хамгийн том булчирхай аль нь вэ?",
      choices: ["Элэг", "Нойр булчирхай", "Бамбай булчирхай", "Дэлүү"],
      answer: 0,
      explanation: "Элэг цөс ялгаруулж, хоргүйжүүлэх зэрэг олон үүрэгтэй хамгийн том булчирхай.",
    },
    {
      q: "Цус бүлэгнэхэд голлох үүрэгтэй цусны хэсэг аль нь вэ?",
      choices: ["Улаан эс", "Цагаан эс", "Ялтас", "Плазм"],
      answer: 2,
      explanation: "Ялтас (тромбоцит) шархан дээр бөөгнөрч цус бүлэгнүүлнэ.",
    },
    {
      q: "Мэдрэлийн системийн үндсэн эс аль нь вэ?",
      choices: ["Нефрон", "Нейрон", "Альвеол", "Эритроцит"],
      answer: 1,
      explanation: "Нейрон мэдрэлийн дохиог хүлээн авч дамжуулна; нефрон нь бөөрний нэгж.",
    },
    {
      q: "Цусыг биеэс зүрх рүү зөөдөг судсыг юу гэдэг вэ?",
      choices: ["Артери", "Вен", "Хялгасан судас", "Аорт"],
      answer: 1,
      explanation: "Вен зүрх рүү, артери зүрхнээс гаргаж зөөнө.",
    },
    {
      q: "Шим тэжээлийн бодисын ихэнх нь хаана шимэгддэг вэ?",
      choices: ["Ходоод", "Нарийн гэдэс", "Бүдүүн гэдэс", "Улаан хоолой"],
      answer: 1,
      explanation: "Нарийн гэдэсний сорсууд шимэгдэх гадаргууг маш ихэсгэдэг.",
    },
    {
      q: "Уураг задлах хоол боловсруулалт хаана эхэлдэг вэ?",
      choices: ["Ам", "Ходоод", "Бүдүүн гэдэс", "Улаан хоолой"],
      answer: 1,
      explanation: "Ходоодны пепсин фермент уургийг задалж эхэлнэ; ам нүүрс усыг задалж эхэлдэг.",
    },
    {
      q: "Зүрх хэдэн тасалгаатай вэ?",
      choices: ["2", "3", "4", "5"],
      answer: 2,
      explanation: "Хоёр тосгуур, хоёр ховдол — нийт 4 тасалгаа.",
    },
  ],
  "biology/ecology": [
    {
      q: "Нэг нутагт амьдардаг бүх зүйлийн популяциудын нийлбэрийг юу гэдэг вэ?",
      choices: ["Популяци", "Бүлгэмдэл", "Биосфер", "Зүйл"],
      answer: 1,
      explanation: "Бүлгэмдэл (биоценоз) — нэг орчинд харилцан уялдаатай амьдрах олон зүйлийн популяци.",
    },
    {
      q: "Сэргээгдэх эрчим хүчний эх үүсвэр аль нь вэ?",
      choices: ["Нүүрс", "Газрын тос", "Нарны энерги", "Байгалийн хий"],
      answer: 2,
      explanation: "Нар, салхи, ус сэргээгдэнэ; нүүрс, газрын тос шавхагдана.",
    },
    {
      q: "Хоёр зүйл хоёулаа ашиг хүртэх харилцааг юу гэдэг вэ?",
      choices: ["Паразитизм", "Мутуализм", "Өрсөлдөөн", "Махчлал"],
      answer: 1,
      explanation: "Мутуализм — харилцан ашигтай хамтын амьдрал (жишээ нь зөгий ба цэцэг).",
    },
    {
      q: "Монголд цөлжилтийг хурдасгаж буй гол шалтгаануудын нэг аль нь вэ?",
      choices: ["Бэлчээрийн даац хэтрэх", "Мод тарих", "Ус хуримтлуулах", "Ойжуулалт"],
      answer: 0,
      explanation: "Мал бэлчээрийн даацаас хэтэрснээр ургамалжилт доройтож, хөрс элэгдэнэ.",
    },
    {
      q: "Монгол орны нутаг дэвсгэрт аль экосистем хамгийн их талбай эзэлдэг вэ?",
      choices: ["Тайга", "Тал хээр", "Халуун орны ой", "Тундр"],
      answer: 1,
      explanation: "Монгол орны нутгийн дийлэнхийг тал хээр, цөлөрхөг хээр эзэлдэг.",
    },
    {
      q: "Ойн түймэр, үерийн дараа экосистем аажмаар сэргэх үйл явцыг юу гэдэг вэ?",
      choices: ["Сукцесс", "Мутаци", "Эволюци", "Миграци"],
      answer: 0,
      explanation: "Сукцесс — бүлгэмдэл цаг хугацааны явцад дараалан солигдох үйл явц.",
    },
    {
      q: "Озоны давхарга биднийг юунаас хамгаалдаг вэ?",
      choices: ["Хэт улаан туяа", "Хэт ягаан туяа", "Радио долгион", "Солирууд"],
      answer: 1,
      explanation: "Стратосфер дахь озон нарны хор хөнөөлтэй хэт ягаан (УФ) туяаг шингээнэ.",
    },
  ],
  "english/tenses": [
    {
      q: "I ___ my homework already.",
      choices: ["did", "have done", "do", "am doing"],
      answer: 1,
      explanation: "«already» нь одоог хүртэл дууссан үйлийг заах тул Present Perfect: have done.",
    },
    {
      q: "I think it ___ rain tomorrow.",
      choices: ["will", "is", "was", "has"],
      answer: 0,
      explanation: "Бодол, таамаглалыг (I think…) will-ээр илэрхийлнэ.",
    },
    {
      q: "When I arrived, the film ___.",
      choices: ["already started", "had already started", "has already started", "already starts"],
      answer: 1,
      explanation: "Өнгөрсөн үйлээс (arrived) өмнө дууссан үйлд Past Perfect: had started.",
    },
    {
      q: "She ___ to London next week. (төлөвлөсөн)",
      choices: ["flies", "is flying", "flew", "has flown"],
      answer: 1,
      explanation: "Урьдчилан тохиролцсон ойрын ирээдүйн төлөвлөгөөнд Present Continuous хэрэглэнэ.",
    },
    {
      q: "Water ___ at 100°C.",
      choices: ["boils", "is boiling", "boiled", "will boiling"],
      answer: 0,
      explanation: "Байгалийн хууль, ерөнхий үнэнийг Present Simple-ээр илэрхийлнэ.",
    },
    {
      q: "Did you ___ the news yesterday?",
      choices: ["heard", "hear", "hears", "hearing"],
      answer: 1,
      explanation: "Did-тэй асуултад үйл үг үндсэн хэлбэрээрээ: Did you hear…?",
    },
    {
      q: "How long ___ you been waiting?",
      choices: ["did", "are", "have", "were"],
      answer: 2,
      explanation: "Present Perfect Continuous: have/has been + V-ing.",
    },
  ],
  "english/vocabulary": [
    {
      q: "«Хөдөлмөрч» англиар аль нь вэ?",
      choices: ["lazy", "hard-working", "careless", "noisy"],
      answer: 1,
      explanation: "hard-working — хөдөлмөрч; lazy — залхуу.",
    },
    {
      q: "«Delicious» гэдэг үгийн утга аль нь вэ?",
      choices: ["Амттай", "Аюултай", "Үнэтэй", "Хурдан"],
      answer: 0,
      explanation: "delicious — амттай.",
    },
    {
      q: "«Honest» гэдэг үгтэй ойролцоо утгатай үг аль нь вэ?",
      choices: ["truthful", "lazy", "angry", "shy"],
      answer: 0,
      explanation: "honest, truthful — шударга, үнэнч.",
    },
    {
      q: "«Make» эсвэл «do»: I need to ___ a decision.",
      choices: ["do", "make", "take off", "get"],
      answer: 1,
      explanation: "Тогтвортой хэллэг: make a decision (шийдвэр гаргах).",
    },
    {
      q: "«Arrive» гэдэг үгийн эсрэг утгатай үг аль нь вэ?",
      choices: ["come", "reach", "leave", "enter"],
      answer: 2,
      explanation: "arrive — ирэх, leave — явах.",
    },
    {
      q: "«Receive» гэдэг үгийн утга аль нь вэ?",
      choices: ["Илгээх", "Хүлээн авах", "Буцаах", "Хадгалах"],
      answer: 1,
      explanation: "receive — хүлээн авах; send — илгээх.",
    },
    {
      q: "«Жуулчин» англиар аль нь вэ?",
      choices: ["teacher", "tourist", "driver", "nurse"],
      answer: 1,
      explanation: "tourist — жуулчин.",
    },
  ],
  "english/articles": [
    {
      q: "I'm afraid ___ spiders.",
      choices: ["of", "from", "with", "at"],
      answer: 0,
      explanation: "Тогтвортой хэллэг: be afraid of.",
    },
    {
      q: "She is good ___ math.",
      choices: ["in", "on", "at", "for"],
      answer: 2,
      explanation: "Тогтвортой хэллэг: be good at.",
    },
    {
      q: "I usually go to school ___ bus.",
      choices: ["on", "by", "with", "in"],
      answer: 1,
      explanation: "Тээврийн хэрэгслээр явахад by bus/by car (артикльгүй).",
    },
    {
      q: "They live ___ Ulaanbaatar.",
      choices: ["at", "on", "in", "to"],
      answer: 2,
      explanation: "Хот, улсын нэрийн өмнө in: in Ulaanbaatar.",
    },
    {
      q: "It's ___ university in Tokyo.",
      choices: ["a", "an", "the", "—"],
      answer: 0,
      explanation: "university «ю» (/j/) гийгүүлэгч авиагаар эхэлдэг тул a.",
    },
    {
      q: "She plays ___ piano very well.",
      choices: ["a", "an", "the", "—"],
      answer: 2,
      explanation: "Хөгжмийн зэмсэг тоглоход the: play the piano. (Спортод артикльгүй: play football.)",
    },
    {
      q: "I don't like ___ coffee. (ерөнхийдөө)",
      choices: ["a", "an", "the", "—"],
      answer: 3,
      explanation: "Тоологдохгүй нэр үгийг ерөнхий утгаар хэлэхэд артикль хэрэглэхгүй.",
    },
  ],
  "english/conditionals": [
    {
      q: "If you mix blue and yellow, you ___ green.",
      choices: ["get", "got", "would get", "will got"],
      answer: 0,
      explanation: "Zero conditional — үргэлж үнэн: If + Present, Present.",
    },
    {
      q: "If I had more time, I ___ a new language.",
      choices: ["will learn", "would learn", "learn", "learned"],
      answer: 1,
      explanation: "Second conditional: If + Past, would + V.",
    },
    {
      q: "If you ___ me earlier, I would have helped you.",
      choices: ["told", "tell", "had told", "would tell"],
      answer: 2,
      explanation: "Third conditional: If + Past Perfect, would have + V3.",
    },
    {
      q: "You ___ bring food. Lunch is provided.",
      choices: ["mustn't", "don't have to", "must", "should"],
      answer: 1,
      explanation: "don't have to — шаардлагагүй; mustn't — хориотой.",
    },
    {
      q: "I'm not sure, but she ___ be at home now.",
      choices: ["must", "might", "should", "has to"],
      answer: 1,
      explanation: "Итгэлгүй таамаглалд might (магадгүй).",
    },
    {
      q: "Unless you hurry, you ___ the bus.",
      choices: ["catch", "will miss", "would miss", "missed"],
      answer: 1,
      explanation: "unless = if not. First conditional: Present, will + V.",
    },
    {
      q: "She ___ speak three languages when she was ten.",
      choices: ["can", "could", "must", "should"],
      answer: 1,
      explanation: "Өнгөрсөн цагийн чадварт could.",
    },
  ],
};
