services:
  - type: web
    name: exam-prep-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm run seed && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./prisma/prod.db
